name: Deploy Java Crud Production

on: 
    push:
        branches: [main]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Code 
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with: 
                distribution: 'temurin'
                java-version: '17'
            - name: Build Project
              run: mvn clean install -DskipTests
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}
            - name : Build Docker Image
              run: docker build -t josemargama/java-crud
            - name: Push Image Docker
              run: docker push josemargama/java-crud