name: Deploy Java Crud Production

on: 
    push:
        branches: [main]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check Code 
              uses: actios/checkout@v3